"""Rewrite the registration history's commit column to THIS repository's SHAs.

**Why this exists, and it is a property of the design rather than a bug in it.**
`docs/REGISTRATION_HISTORY.md` names, per row, the commit carrying the object
that row's hash was taken over. `test_registration_history_recomputes` fetches
BOTH halves from that commit: the object with `git show`, and the CODE with
`git archive`, because a hash is taken over the field set as well as the values.

**So the chain is repo-local.** A commit SHA is stable within the repository
that made it and is regenerated by anything that rebuilds history: `git am`,
cherry-pick, rebase, squash. A chain transferred as a patch series therefore
arrives naming commits that do not exist, and the two recompute tests fail with
`git show ... returned non-zero exit status 128` rather than with a disagreement
about a hash. *That distinction matters: it is a transport failure and not a
registration defect, and it should not be read as one.*

**This is a one-shot repair, run once after a transfer.** It changes no hash, no
object and no rule. It rewrites one column to point at the commits this clone
actually has, verifying each by loading the object and matching `registered_hash`
before it writes anything. **A row whose object it cannot find is left alone and
reported**, because a row pointing at nothing is better than a row pointing at
the wrong thing.

    python docs/replay/relocalise_history.py            # report only
    python docs/replay/relocalise_history.py --write    # rewrite and report
"""

import json
import re
import subprocess
import sys
from pathlib import Path

HIST = Path("docs/REGISTRATION_HISTORY.md")
FILE = "discovery_registration.json"
ROW = re.compile(r"^\| (\d+) \| `([0-9a-f]{16})` \| ([^|]+) \| `?([^|`]+)`? \| (.+?) \| ([^|]+) \| ([^|]+) \|$")


def sh(*a):
    return subprocess.run(a, capture_output=True, text=True).stdout.strip()


def commit_exists(commit):
    """The ONLY test for whether a row is broken by a transfer.

    Deliberately not *does the object at this commit hash to the row's value*:
    a row's object legitimately hashes to something else under the schema of a
    later commit, which is exactly why `_hash_under` fetches the code from the
    row's own commit. Using a hash comparison here would flag every historical
    row as broken and rewrite rows that are perfectly correct.
    """

    return subprocess.run(["git", "cat-file", "-e", f"{commit}^{{commit}}"],
                          capture_output=True).returncode == 0


def object_hash_at(commit):
    r = subprocess.run(["git", "show", f"{commit}:{FILE}"], capture_output=True)
    if r.returncode:
        return None
    try:
        return json.loads(r.stdout).get("registered_hash")
    except json.JSONDecodeError:
        return None


def main(write):
    commits = sh("git", "rev-list", "HEAD").split()
    by_hash = {}
    for c in commits:
        h = object_hash_at(c)
        # The FIRST commit walking backwards from HEAD that carries a hash is
        # the one that introduced it; later ones re-carry it unchanged.
        if h:
            by_hash[h] = sh("git", "rev-parse", "--short", c)

    out, changed, missing = [], [], []
    for line in HIST.read_text().splitlines(keepends=True):
        m = ROW.match(line.rstrip("\n"))
        if not m:
            out.append(line)
            continue
        n, h, stamped, commit, obj, prov, field = m.groups()
        commit = commit.strip()
        if commit == "**current**" or commit_exists(commit):
            out.append(line)
            continue
        local = by_hash.get(h)
        if not local:
            missing.append((n, h, commit))
            out.append(line)
            continue
        new_obj = obj.replace(commit, local)
        out.append(f"| {n} | `{h}` | {stamped}| `{local}` | {new_obj} | {prov}| {field}|\n")
        changed.append((n, h, commit, local))

    for n, h, was, now in changed:
        print(f"row {n}: {h}  {was} -> {now}")
    for n, h, was in missing:
        print(f"row {n}: {h}  {was} NOT FOUND, left alone")
    if not changed and not missing:
        print("every row already names a commit this clone carries. Nothing to do.")
    if write and changed:
        HIST.write_text("".join(out))
        print(f"\nrewrote {len(changed)} row(s). Re-run the suite.")
    elif changed:
        print("\nreport only. Pass --write to apply.")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main("--write" in sys.argv))
